version: '3.9'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./front:/app
