FROM node:22-alpine AS build
WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm ci --production


# generer les type prisma
COPY prisma ./prisma
RUN npx prisma generate

# Copier les fichiers sources
COPY . .

# build l'application
RUN npm install typescript -g
RUN npm run build

FROM node:22-alpine
WORKDIR /app

# Copier les fichiers de l'étape précédente
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/build ./build
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/package-lock.json ./package-lock.json

# Exposer le port 3000
EXPOSE 3000

# Démarrer l'application
CMD ["npm", "start"]

